package connection;

public enum Request {
	INIT_GAME, FAIL_INIT_GAME, SEND_INFO_GOALS, SEND_INFO_PLAYERS, SEND_ID_USER, RECIBE_INFO_PLAYER, SEND_INFO, REFRESH_PLAYERS, SEND_INFO_BALL, SEND_INFO_POINTS, SEND_SECONDS
}